'use strict';
// API
 var HOST_URL = "192.168.1.120";




// Declare app level module which depends on views, and components
angular.module('myApp', [
    'ngRoute',
    'ngMaterial',
    'ngAnimate',
    'ngAria',
    'myApp.repayment_table',
    'myApp.information_autable',


    // 'myApp.information_audit',
    'myApp.news_add',  
    'myApp.news_view',
    'myApp.news_edit',
    // 'myApp.indeximg_add',
    // 'myApp.indeximg_view',
    //  'myApp.indeximg_edit',
    'myApp.loan_cash',
    'myApp.investor_cash',
    'myApp.investor_recharge',
    'myApp.loan_recharge',
    'myApp.userAdd',
    'myApp.userEdit',
    'myApp.userView',
    'myApp.plan_add',
    'myApp.loan_add',
    'myApp.plan_detail',
    'myApp.plan_edit',
    'myApp.plan_ready',
    'myApp.plan_view',
    'myApp.loanView',
    'myApp.loanEdit',
    'myApp.loanDetail',
    'myApp.activity',
    'myApp.investor',
    'myApp.investor_add',
    'myApp.investor_edit',
    'myApp.investor_potential',
    // 'myApp.loan_detail',
    'myApp.loan_view',
    'myApp.loan_edit',
    // 'myApp.loan_peopledetail',
    'myApp.loan_plan',
    'myApp.investor_view', 

    'myApp.filter',
    'myApp.layout',
    'myApp.userPassword',
    'myApp.login',
    'myApp.logout',
    'myApp.index',
    'myApp.loan_borrower',
    'myApp.automatic_detail',
    'myApp.automatic_edit',
    'myApp.express',
    // 'myApp.shuju',
    'myApp.recharge_list',
    'myApp.activity_new',
    'myApp.search2016',
    'myApp.commend',
    'myApp.query_order',
    'myApp.search',
    'myApp.card_list',
    'myApp.card_edit',
    'myApp.account_list',
    'myApp.tradeRecord',

    'myApp.investmentRecord',

    'myApp.repay_list',
    'myApp.banner_add',
    'myApp.banner_list',
    'myApp.indexMobileEdit',
    'myApp.indexEdit',
    'myApp.notice_view',
    'myApp.notice_edit',
    'myApp.notice_add',
    'myApp.help_view',
    'myApp.help_edit',
    'myApp.help_add',
    'myApp.borrower',
    'myApp.repayExamine',
    'myApp.statistics_list',
    'myApp.offline',
    'myApp.pocket',
    'myApp.check_list',
    'myApp.personal_list',
    // 'myApp.grant_list',
    // 'myApp.regular',
    // 'myApp.coupon',
    'myApp.couponRegular',
    'myApp.dataCenter',
    'myApp.couponRegular_add',
    'myApp.couponRegular_edit',
    'myApp.voucherUser',
    'myApp.voucherCash',
    'myApp.grantPocket',
    'myApp.activity_list',
    'myApp.activityEdit',
    'myApp.activityMobileEdit',
    'myApp.activity_add',
    'myApp.todayRepay',
    'myApp.openScreen_list',
    'myApp.openScreen_add',
    'myApp.openScreenEdit',
    'myApp.openScreenIosEdit',
    'myApp.propel',
    'myApp.propel_list',
    'myApp.propelEdit',
    'myApp.todayRepayExamine',
    'myApp.withdrawalExamine',
    'myApp.update_list',
    'myApp.updateEdit',
    'myApp.updateIosEdit',
    'myApp.update_add',
    'myApp.partners_list',
    'myApp.partnersEdit',
    'myApp.partners_add',
     //银行卡管理

    'myApp.firstInvestmentRecord',//首投记录



]).config(['$routeProvider', function($routeProvider) {
    $routeProvider.otherwise({ redirectTo: '/login' });
}]);